### PR TITLE
ensure mesh is local to spline when using "self"

### PR DESCRIPTION
**Pull request by thnewlands**
To do this I transform the mesh back from world space to local after creating it in world space.

### CODE REVIEW

**Comment by coty-crg** [comment]
Are you sure its only when using 'self'? It looks like it always transforms it to local space.

**Comment by coty-crg** [comment]
By the way, thanks for these pull requests. Appreciate it!

**Comment by thnewlands** [comment]
Oh!! Good point!! I came up with these pretty fast without checking some of my work!! Definitely needs an if statement for that transformation.

**Comment by coty-crg** [comment]
Can you add in the check? I'll merge in the pull request after that addition. Thanks!

**Comment by thnewlands** [comment]
Done!

**Pull request merged**
